#testing dev deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-dev
  namespace: dev
spec:
  project: default

  source:
    repoURL: https://github.com/vishyswaminathan/helm-manifest-nodeapp.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
