apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-staging
  namespace: staging
spec:
  project: default

  source:
    repoURL: https://github.com/vishyswaminathan/helm-manifest-nodeapp.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
