replicaCount: 1

app:
  name: nodeapp
  image:
    repository: vishyswaminathan/nodeapp
    tag: "v54"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

environment: development
